import {Entity, model, property} from '@loopback/repository';

export const OAUTH_CLIENT_TYPE = {
  Web: 'web',
  Mobile: 'mobile',
} as const;

export type OAuthClientType =
  (typeof OAUTH_CLIENT_TYPE)[keyof typeof OAUTH_CLIENT_TYPE];

@model({
  settings: {
    // State is generated by SessionService, not by the database.
    forceId: false,
    postgresql: {schema: 'auth', table: 'oauth_transaction'},
  },
})
export class OAuthTransaction extends Entity {
  @property({
    type: 'string',
    id: true,
    required: true,
    postgresql: {dataType: 'text'},
  })
  state!: string;

  @property({
    type: 'string',
    required: true,
    postgresql: {columnName: 'code_verifier', dataType: 'text'},
  })
  codeVerifier!: string;

  @property({
    type: 'string',
    required: true,
    jsonSchema: {enum: Object.values(OAUTH_CLIENT_TYPE)},
    postgresql: {columnName: 'client_type', dataType: 'text'},
  })
  clientType!: OAuthClientType;

  @property({
    type: 'string',
    required: true,
    postgresql: {columnName: 'redirect_uri', dataType: 'text'},
  })
  redirectUri!: string;

  @property({
    type: 'date',
    required: true,
    defaultFn: 'now',
    postgresql: {columnName: 'created_at', dataType: 'timestamptz'},
  })
  createdAt!: Date;

  @property({
    type: 'date',
    required: true,
    postgresql: {columnName: 'expires_at', dataType: 'timestamptz'},
  })
  expiresAt!: Date;

  constructor(data?: Partial<OAuthTransaction>) {
    super(data);
  }
}
